name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get project files
      uses: actions/checkout@v2
    - name: Install global dependencies
      run: sudo npm i -g @quasar/cli
    - name: Install project dependencies
      run: yarn install --ignore-optional --pure-lockfile --non-interactive
    - name: Build Quasar project
      run: yarn build
    - name: Copy CNAME to dist folder
      run: cp CNAME dist/spa/CNAME
    - name: Deploy to GitHub Pages
      uses: LuisEnMarroquin/gh-pages-publish@v2.3.4
      with:
        FOLDER: dist/spa
        SSHKEY: ${{ secrets.SSH }}
